# Generated by Django 2.2.13 on 2020-08-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='T1',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('n_star', models.IntegerField()),
                ('short', models.CharField(max_length=400)),
                ('sentiment', models.FloatField()),
            ],
            options={
                'db_table': 't1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tb2',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('movie_name', models.CharField(blank=True, max_length=255, null=True)),
                ('movie_type', models.CharField(blank=True, max_length=255, null=True)),
                ('movie_time', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tb2',
                'managed': False,
            },
        ),
    ]
